interface SeedProduct {
  description: string;
  images: string[];
  inStock: number;
  price: number;
  sizes: ValidSizes[];
  slug: string;
  tags: string[];
  title: string;
  type: ValidTypes;
  gender: "hombre" | "mujer" | "unisex";
}

type ValidSizes = "XS" | "S" | "M" | "L" | "XL" | "XXL" | "3XL";
type ValidTypes = "camisetas" | "buzos" | "Productos";

interface SeedData {
  products: SeedProduct[];
}

export const initialData: SeedData = {
  products: [
    {
      description:
        "Te presentamos a tu nueva camiseta favorita. Esta camiseta adidas clásica luce un ajuste ceñido y un dobladillo en contraste para crear un look vintage único. Combínala con tus jeans oscuros favoritos y logra un estilo clásico y descomplicado. Está confeccionada en algodón supersuave que ofrece comodidad en todo momento.",
      images: ["rubiano_Uno.jpg", "rubiano.jpg"],
      inStock: 7,
      price: 150000,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      slug: "camiseta-logo-cent-developer-android",
      type: "camisetas",
      tags: ["sweatshirt"],
      title: "Camiseta 3 Rayas Adicolor ",
      gender: "hombre",
    },
    {
      description:
        "Te presentamos a tu nueva camiseta favorita. Esta camiseta adidas clásica luce un ajuste ceñido y un dobladillo en contraste para crear un look vintage único. Combínala con tus jeans oscuros favoritos y logra un estilo clásico y descomplicado. Está confeccionada en algodón supersuave que ofrece comodidad en todo momento.",
      images: ["AdidasAzul.jpg", "cadena.jpg"],
      inStock: 5,
      price: 150000,
      sizes: ["XS", "S", "M", "XL", "XXL"],
      slug: "camiseta-logo-cent-developer-angular",
      type: "camisetas",
      tags: ["angular"],
      title: "Camiseta 3 Rayas Adicolor",
      gender: "hombre",
    },
    {
      description: "Descubre la esencia de la comodidad ",
      images: ["AdidasBlanc.jpg", "AdidasBlanc1.jpg"],
      inStock: 13,
      price: 150000,
      sizes: ["S", "M", "L", "XL", "XXL"],
      slug: "camiseta-logo-cent-developer-archlnux",
      type: "camisetas",
      tags: ["archlinux"],
      title: "Camiseta 3 Rayas Adicolor",
      gender: "hombre",
    },
    {
      description:
        "Te presentamos a tu nueva camiseta favorita. Esta camiseta adidas clásica luce un ajuste ceñido y un dobladillo en contraste para crear un look vintage único. Combínala con tus jeans oscuros favoritos y logra un estilo clásico y descomplicado. Está confeccionada en algodón supersuave que ofrece comodidad en todo momento.",
      images: ["AdidasVer.jpg", "AdidasVer1.jpg"],
      inStock: 50,
      price: 130000,
      sizes: ["XS", "S", "M", "L"],
      slug: "camiseta-logo-cent-developer-aws",
      type: "camisetas",
      tags: ["aws"],
      title: "Camiseta Adicolor Classics",
      gender: "hombre",
    },
    {
      description:
        "Te presentamos a tu nueva camiseta favorita. Esta camiseta adidas clásica luce un ajuste ceñido y un dobladillo en contraste para crear un look vintage único. Combínala con tus jeans oscuros favoritos y logra un estilo clásico y descomplicado. Está confeccionada en algodón supersuave que ofrece comodidad en todo momento.",
      images: ["AdidasNeg.jpg", "AdidasNeg1.jpg"],
      inStock: 50,
      price: 130000,
      sizes: ["M", "L", "XL", "XXL"],
      slug: "camiseta-logo-cent-developer-aws-azure",
      type: "camisetas",
      tags: ["azure", "aws"],
      title: "Camiseta Adicolor Classics",
      gender: "hombre",
    },
    {
      description:
        "Te presentamos a tu nueva camiseta favorita. Esta camiseta adidas clásica luce un ajuste ceñido y un dobladillo en contraste para crear un look vintage único. Combínala con tus jeans oscuros favoritos y logra un estilo clásico y descomplicado. Está confeccionada en algodón supersuave que ofrece comodidad en todo momento..",
      images: ["Adidas_Azul.jpg", "Adidas_Azu1.jpg"],
      inStock: 0,
      price: 130000,
      sizes: ["M", "L", "XL", "XXL"],
      slug: "camiseta-logo-cent-developer-azure",
      type: "camisetas",
      tags: ["azure"],
      title: "Camiseta Adicolor Classics",
      gender: "hombre",
    },
    {
      description:
        "Una prenda esencial que irradia comodidad. El look minimalista de estas licras adidas se actualiza con un toque deportivo al incorporar el logo en vertical en la pierna izquierda. Su diseño de pretina alta les confiere un estilo urbano único.",
      images: ["licr_1.jpg", "licr.jpg"],
      inStock: 15,
      price: 69000,
      sizes: ["S", "M", "L", "XL"],
      slug: "camiseta-logo-cent-developer-css",
      type: "camisetas",
      tags: ["css"],
      title: "Licra Essentials",
      gender: "mujer",
    },
    {
      description:
        "Una prenda esencial que irradia comodidad. El look minimalista de estas licras adidas se actualiza con un toque deportivo al incorporar el logo en vertical en la pierna izquierda. Su diseño de pretina alta les confiere un estilo urbano único.",
      images: ["LicNeg.jpg", "LicNegra.jpg"],
      inStock: 15,
      price: 69000,
      sizes: ["S", "M", "L", "XL"],
      slug: "camiseta-logo-cent-docker",
      type: "camisetas",
      tags: ["docker"],
      title: "Licra Essentials",
      gender: "mujer",
    },
    {
      description:
        "Una prenda esencial que irradia comodidad. El look minimalista de estas licras adidas se actualiza con un toque deportivo al incorporar el logo en vertical en la pierna izquierda. Su diseño de pretina alta les confiere un estilo urbano único..",
      images: ["LicRosa.jpg", "LicRosa1.jpg"],
      inStock: 15,
      price: 118000,
      sizes: ["S", "M", "L", "XL"],
      slug: "camiseta-logo-cent-developer-Cisco",
      type: "camisetas",
      tags: ["Cisco"],
      title: "Licra Essentials",
      gender: "mujer",
    },
    {
      description:
        "Confeccionado con un suave tejido French terry para ofrecer una comodidad informal para el día a día, nuestro pantalón corto Nike Club Alumni cuenta con bordes sin rematar en las aberturas de los bolsillos y en el dobladillo para que luzcas un look vintage y desgastado. Tanto si vas a hacer recados por el campus como si te apetece dejarte llevar por la nostalgia, la cintura elástica cuenta con un cordón exterior para que puedas encontrar el ajuste perfecto.",
      images: ["Nike.jpg", "Nike1.jpg"],
      inStock: 15,
      price: 85000,
      sizes: ["S", "M", "L", "XL"],
      slug: "camiseta-logo-cent-developer-Csharp",
      type: "camisetas",
      tags: ["Csharp"],
      title: "Nike Club Alumni",
      gender: "hombre",
    },
    {
      description:
        "Confeccionado con un suave tejido French terry para ofrecer una comodidad informal para el día a día, nuestro pantalón corto Nike Club Alumni cuenta con bordes sin rematar en las aberturas de los bolsillos y en el dobladillo para que luzcas un look vintage y desgastado. Tanto si vas a hacer recados por el campus como si te apetece dejarte llevar por la nostalgia, la cintura elástica cuenta con un cordón exterior para que puedas encontrar el ajuste perfecto.",
      images: ["NikeAzul.jpg", "NikeAzu1.jpg"],
      inStock: 15,
      price: 85000,
      sizes: ["S", "M", "L", "XL"],
      slug: "camiseta-logo-cent-developer-Edubuntu",
      type: "camisetas",
      tags: ["Edubuntu"],
      title: "Nike Club Alumniu",
      gender: "hombre",
    },
    {
      description:
        "Confeccionado con un suave tejido French terry para ofrecer una comodidad informal para el día a día, nuestro pantalón corto Nike Club Alumni cuenta con bordes sin rematar en las aberturas de los bolsillos y en el dobladillo para que luzcas un look vintage y desgastado. Tanto si vas a hacer recados por el campus como si te apetece dejarte llevar por la nostalgia, la cintura elástica cuenta con un cordón exterior para que puedas encontrar el ajuste perfecto.",
      images: ["NikeNeg.jpg", "NikeNeg1.jpg"],
      inStock: 15,
      price: 85000,
      sizes: ["S", "M", "L", "XL"],
      slug: "camiseta-logo-cent-developer-Flutter",
      type: "camisetas",
      tags: ["Flutter"],
      title: "Nike Club Alumni",
      gender: "hombre",
    },
    {
      description:
        "La camiseta tradicional de toda la vida Corte recto, clásico y holgado Tejido grueso de 180 g/m² de gramaje, colores lisos en algodón sanforizado. El color gris jaspeado es 90 % algodón y 10 % poliéster; el denim jaspeado es 50 % poliéster. Cuello y dobladillos con doble puntada para una mayor durabilidad La imprenta independiente que imprime este producto ha sido evaluada de acuerdo con los estándares de la Organización Internacional del Trabajo.La imprenta independiente que imprime este producto obtiene sus materiales de fabricantes comprometidos con la mejora de las prácticas de cultivo de algodón.",
      images: ["Nike_A.jpg", "Nike_B.jpg"],
      inStock: 15,
      price: 69000,
      sizes: ["S", "M", "L", "XL"],
      slug: "camiseta-logo-cent-developer-Github",
      type: "camisetas",
      tags: ["Github"],
      title: "Nike Pro 365",
      gender: "mujer",
    },
    {
      description:
        "La camiseta tradicional de toda la vida Corte recto, clásico y holgado Tejido grueso de 180 g/m² de gramaje, colores lisos en algodón sanforizado. El color gris jaspeado es 90 % algodón y 10 % poliéster; el denim jaspeado es 50 % poliéster. Cuello y dobladillos con doble puntada para una mayor durabilidad La imprenta independiente que imprime este producto ha sido evaluada de acuerdo con los estándares de la Organización Internacional del Trabajo.La imprenta independiente que imprime este producto obtiene sus materiales de fabricantes comprometidos con la mejora de las prácticas de cultivo de algodón.",
      images: ["NikeC.jpg", "Nike_C.jpg"],
      inStock: 15,
      price: 69000,
      sizes: ["S", "M", "L", "XL"],
      slug: "camiseta-logo-cent-developer-Github-copilot",
      type: "camisetas",
      tags: ["Github"],
      title: "Nike Pro 365",
      gender: "mujer",
    },
    {
      description:
        "La camiseta tradicional de toda la vida Corte recto, clásico y holgado Tejido grueso de 180 g/m² de gramaje, colores lisos en algodón sanforizado. El color gris jaspeado es 90 % algodón y 10 % poliéster; el denim jaspeado es 50 % poliéster. Cuello y dobladillos con doble puntada para una mayor durabilidad La imprenta independiente que imprime este producto ha sido evaluada de acuerdo con los estándares de la Organización Internacional del Trabajo.La imprenta independiente que imprime este producto obtiene sus materiales de fabricantes comprometidos con la mejora de las prácticas de cultivo de algodón.",
      images: ["NikeD.jpg", "Nike_D.jpg"],
      inStock: 15,
      price: 69000,
      sizes: ["S", "M", "L", "XL"],
      slug: "camiseta-logo-cent-developer-Github-copilot",
      type: "camisetas",
      tags: ["Github"],
      title: "Nike Pro 365",
      gender: "mujer",
    },
    {
      description:
        "La camiseta Ready con capilarización del sudor mantiene la frescura durante todas tus actividades de fitness. Cuenta con un ajuste holgado y un tejido transpirable de secado rápido para mantener la frescura cuando el entrenamiento se intensifica. Además, cuenta con mangas angulares para facilitar el movimiento, tanto al levantar pesas en el gimnasio como al estirar al aire libre.",
      images: ["NikCam.jpg", "NikCam1.jpg"],
      inStock: 15,
      price: 75000,
      sizes: ["S", "M", "L", "XL"],
      slug: "camiseta-logo-cent-developer-Github-copilot",
      type: "camisetas",
      tags: ["Github"],
      title: "Nike Ready",
      gender: "hombre",
    },
    {
      description:
        "La camiseta Ready con capilarización del sudor mantiene la frescura durante todas tus actividades de fitness. Cuenta con un ajuste holgado y un tejido transpirable de secado rápido para mantener la frescura cuando el entrenamiento se intensifica. Además, cuenta con mangas angulares para facilitar el movimiento, tanto al levantar pesas en el gimnasio como al estirar al aire libre.",
      images: ["NikeVer.jpg", "NikeVer1.jpg"],
      inStock: 15,
      price: 75000,
      sizes: ["S", "M", "L", "XL"],
      slug: "camiseta-logo-cent-developer-Github-copilot",
      type: "camisetas",
      tags: ["Github"],
      title: "Nike Ready",
      gender: "hombre",
    },
    {
      description:
        "La camiseta Ready con capilarización del sudor mantiene la frescura durante todas tus actividades de fitness. Cuenta con un ajuste holgado y un tejido transpirable de secado rápido para mantener la frescura cuando el entrenamiento se intensifica. Además, cuenta con mangas angulares para facilitar el movimiento, tanto al levantar pesas en el gimnasio como al estirar al aire libre.",
      images: ["NikeCaf.jpg", "NikeCaf1.jpg"],
      inStock: 15,
      price: 75000,
      sizes: ["S", "M", "L", "XL"],
      slug: "gorra-tech-github",
      type: "Productos",
      tags: ["github"],
      title: "Nike Ready",
      gender: "hombre",
    },
    {
      description:
        "Alimento en polvo a base de Proteína aislada de suero 65%, Caseína Micelar 35% y Leucina 3g.",
      images: ["BestCoco.JPG", "BestTabla.JPG"],
      inStock: 15,
      price: 199000,
      sizes: ["S", "M", "L", "XL"],
      slug: "gorra-tech-react",
      type: "Productos",
      tags: ["react"],
      title: "Best 2.04 LB",
      gender: "unisex",
    },
    {
      description:
        "Alimento en polvo a base de Proteína aislada de suero 65%, Caseína Micelar 35% y Leucina 3g.",
      images: ["Best5Lb.JPG", "Tabla5Lb.JPG"],
      inStock: 15,
      price: 370000,
      sizes: ["S", "M", "L", "XL"],
      slug: "gorra-tech-js",
      type: "Productos",
      tags: ["js"],
      title: "Best 4 LB",
      gender: "unisex",
    },
    {
      description:
        "Alimento en polvo a base de Proteína aislada de suero 65%, Caseína Micelar 35% y Leucina 3g.",
      images: ["BEST4LBBOLSAS.JPG", "bestBolsaTabla.JPG"],
      inStock: 15,
      price: 370000,
      sizes: ["S", "M", "L", "XL"],
      slug: "gorra-tech-ubuntu",
      type: "Productos",
      tags: ["ubuntu"],
      title: "Best 4 LB Bolsa",
      gender: "unisex",
    },
    {
      description:
        "Bipro Classic es una proteína de suero de alta pureza y concentración, con mínimos niveles de grasa y lactosa.",
      images: ["BiPro.JPG", "BiPro6lb.JPG"],
      inStock: 15,
      price: 149000,
      sizes: ["S", "M", "L", "XL"],
      slug: "gorra-tech-angular",
      type: "Productos",
      tags: ["angular"],
      title: "Bipro Classic",
      gender: "unisex",
    },
    {
      description:
        "Proton Whey, es una mezcla en polvo a base de proteina concentrada y aislada de suero lácteo con probióticos.",
      images: ["Proton.JPG", "Proton6lb.JPG"],
      inStock: 15,
      price: 126000,
      sizes: ["S", "M", "L", "XL"],
      slug: "buzo-you-are-special",
      type: "buzos",
      tags: ["special"],
      title: "Proton Whey",
      gender: "hombre",
    },
    {
      description:
        "ISO 100 es una proteína de suero aislado de leche de la marca DYMATIZE ha sido procesada para llegar a la perfección, 100% hidrolizada e instantánea y a través de 5 controles diferentes de calidad.",
      images: ["Iso.JPG", "iso100.JPG"],
      inStock: 15,
      price: 210000,
      sizes: ["S", "M", "L", "XL"],
      slug: "buzo-you-are-frontend",
      type: "buzos",
      tags: ["frontend"],
      title: "ISO 100",
      gender: "hombre",
    },
    {
      description:
        "Polvo Deshidratado De Frutos Rojos, L-Citrulina, Beta-Alanina, Creatina HCl, PolvoDe Raíz De Remolacha, L-Leucina, L-Arginina, Betaína, L-Isoleucina, L-Valina, Dióxido De Silicio(Anticompactante), Cafeína, Sucralosa (Edulcorante), Saborizante Idéntico Al Natural, Aspartame(Edulcorante), Goma Xanthan (Espesante), Citrato De Zinc, Ácido Cítrico (Ácidulante), ÁcidoMálico (Acidulante), Niacina (Vitamina B3), Silicato de Calcio, Benzoato De Sodio (Conservante), Colorante Rojo FD&C CI 45430, Pimienta En Polvo, Piridoxina Clorhidrato, Tiamina Clorhidrato, Vitamina D3, Selenito De Sodio.",
      images: ["Intenze.JPG", "Intenze1.JPG"],
      inStock: 15,
      price: 140000,
      sizes: ["S", "M", "L", "XL"],
      slug: "buzo-you-are-dev",
      type: "buzos",
      tags: ["dev"],
      title: "Intenze",
      gender: "hombre",
    },
    {
      description:
        "ELECTRON es una mezcla en polvo a base de fruta micro pulverizada, que tiene ingredientes como Taurina, Tirosina, Cafeina, entre otros.",
      images: ["Electron.JPG", "Electron.JPG"],
      inStock: 15,
      price: 125000,
      sizes: ["S", "M", "L", "XL"],
      slug: "buzo-you-are-hello-world",
      type: "buzos",
      tags: ["hello-world"],
      title: "Electron",
      gender: "hombre",
    },
    {
      description:
        "Mejora el rendimiento físico y deportivo ya que estimula el sistema nervioso central aumentando el estado de alerta y concentración. Es un verdadero estallido de energía, ideal para todos los deportes de actividad prolongada. Aumenta el estado de alerta y concentración. Mejora el rendimiento físico y deportivo.",
      images: ["Energy.JPG", "Energ.JPG"],
      inStock: 15,
      price: 35000,
      sizes: ["S", "M", "L", "XL"],
      slug: "buzo-you-are-binary",
      type: "buzos",
      tags: ["binary"],
      title: "Energy Up",
      gender: "hombre",
    },
    {
      description:
        "Smart es un Alimento en polvo a base harina de avena con palatinosa, amilopectina, proteina de suero de leche enriquecido con vitaminas.",
      images: ["Smart.JPG", "Smart6lb.JPG"],
      inStock: 15,
      price: 85000,
      sizes: ["S", "M", "L", "XL"],
      slug: "buzo-you-are-phone",
      type: "buzos",
      tags: ["phone"],
      title: "Smart gainer",
      gender: "hombre",
    },
    {
      description:
        "Proteina Hipercalorica de 3 y 6 libras sin azúcar con 40 g de Whey protein, cuenta con 970 calorías y 190 g de carbohidratos ideal para una etapa de volumen y llegar al peso ideal, cuenta con 3 g de creatina HCL y 10g de aminoácidos, cuenta con albumina de huevo y avena haciéndola una proteína con un alto grado de pureza y componentes naturales.",
      images: ["Golden.JPG", "GoldenTABLA.JPG"],
      inStock: 15,
      price: 126000,
      sizes: ["S", "M", "L", "XL"],
      slug: "buzo-you-are-cloud",
      type: "buzos",
      tags: ["cloud"],
      title: "Golden mass",
      gender: "hombre",
    },
    {
      description:
        "Proteína de suero, hipercalórica que incluye en su innovadora fórmula 3000 mg de Creatina, HMB, BCAA, 44g de Proteína, 1000 calorías por porción y fuentes de Carbohidratos con diferentes velocidades de absorción.",
      images: ["Megaplex.JPG", "Megaple.JPG"],
      inStock: 15,
      price: 219000,
      sizes: ["S", "M", "L", "XL"],
      slug: "buzo-you-are-cloud-2",
      type: "buzos",
      tags: ["cloud"],
      title: "Megaplez Power",
      gender: "unisex",
    },
    {
      description:
        "Creatina Monohidrato de 5g para aumento de centímetro de músclo magro. Fuerza, energía y resistencia durante la rutina de entrenamiento.",
      images: ["creatina.JPG", "Crea100.JPG"],
      inStock: 15,
      price: 135000,
      sizes: ["S", "M", "L", "XL"],
      slug: "buzo-you-are-python",
      type: "buzos",
      tags: ["python"],
      title: "Crea 100%",
      gender: "hombre",
    },
    {
      description:
        "Es una elección sobresaliente para aquellos que buscan maximizar su absorción y eficacia, ya que se trata de una creatina monohidratada y micronizada de la más alta pureza.",
      images: ["Creatine.JPG", "Creati.JPG"],
      inStock: 15,
      price: 68000,
      sizes: ["S", "M", "L", "XL"],
      slug: "buzo-you-are-chrome",
      type: "buzos",
      tags: ["chrome"],
      title: "Creatine Time",
      gender: "hombre",
    },
    {
      description:
        "Polvo Deshidratado de Frutas de Uva, Creatina HCL, Sucralosa (Edulcorante), Saborizante Idéntico al Natural, Aspartame (Edulcorante), Goma Xanthan (Espesante), Benzoato de Sodio (Conservante), Ácido Citrico (Acidulante), Ácido Málico (Acidulante), Dióxido de Silicio(Anticompactante), Silicato de Calcio (Espesante), Colorante Rojo FD&C CI 45430. Fenilcetonuricos: Contiene Fenilalanina.",
      images: ["Legacy.JPG", "Legacy.JPG"],
      inStock: 15,
      price: 110000,
      sizes: ["S", "M", "L", "XL"],
      slug: "buzo-you-are-atom",
      type: "buzos",
      tags: ["atom"],
      title: "Legacy",
      gender: "hombre",
    },
    {
      description:
        "Hydroxycut Hardcore Elite NUEVA PRESENTACIÓN de Muscletech Performance Series es una fórmula termogénica, diseñada combinando ingredientes clave en las cantidades precisas con objetivo ofrecer una fórmula muy completa pero sencilla, sin mezclas patentadas con el propósito de incrementar el gasto energético facilitando a la vez la información exacta de que se está tomando.",
      images: ["Muscletech.JPG", "Muscletech.JPG"],
      inStock: 15,
      price: 105000,
      sizes: ["S", "M", "L", "XL"],
      slug: "buzo-you-are-hola",
      type: "buzos",
      tags: ["hola"],
      title: "Hydroxycut",
      gender: "hombre",
    },
    {
      description:
        "Es un producto de última generación diseñado para complementar tu plan nutricional. Contiene ingredientes ampliamente estudiados y aprobados por la FDA: Extracto de naranja amarga, picolinato de cromo, cla, l-carnitina, cafeína, taurina y goma guar.",
      images: ["Burner.JPG", "Burner.JPG"],
      inStock: 15,
      price: 139000,
      sizes: ["S", "M", "L", "XL"],
      slug: "buzo-you-are-emberd",
      type: "buzos",
      tags: ["emberd"],
      title: "Burner Stark",
      gender: "hombre",
    },
    {
      description:
        "Lipo 6 Black Hers Ultra es un producto termogénico pensado especialmente para ayudar a las mujeres en sus procesos de pérdida de peso o definición.",
      images: ["Lipo6.JPG", "Lipo6.JPG"],
      inStock: 15,
      price: 126000,
      sizes: ["S", "M", "L", "XL"],
      slug: "buzo-you-are-id",
      type: "buzos",
      tags: ["dev-id"],
      title: "Lipo 6 Black Hers Ultra",
      gender: "hombre",
    },
  ],
};
